### ISSUE TITLE
Pandas append is deprecated

### ISSUE THREAD

**Issue by MaximilianKarl** [gotec/git2net#31]
**Describe the bug**
Using .append on a pandas DataFrame is deprecated and is printing out a warning

**To Reproduce**
install pandas 1.4.0
install git2net 1.5.3

**Expected behavior**
While mining a repository mutiple warnings will be printed
e.g.:
~\git2net\extraction.py:1092: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_edits = df_edits.append(_extract_edits_merge(git_repo, commit,

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Link to pandas concat:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

**Comment by gotec** [comment]
Thanks a lot for noticing this. I will try to look into it over the weekend.

Cheers,
Christoph

**Comment by gotec** [comment]
Checking the Pandas documentation, I found that the warning only shows up for pandas 1.4 which was released on January the 22nd, i.e. 3 days before you submitted the issue for Python 3.8 and above. It would have probably taken me a while to upgrade and notice, so again, thanks for letting me know so quickly!

Version 1.5.4 of git2net is now using the recommended `pandas.concat` instead of `append`. This version is out on PyPI as of now. Please feel free to close the issue if you can confirm git2net now runs as expected for you, too. Otherwise, I'll do so in a couple of days.

Best,
Christoph

**Comment by MaximilianKarl** [comment]
There is still one left in extraction.py:757

**Comment by gotec** [comment]
Fixed with 33288bd380cb606b13ed9cdc9b2e6f298d0b0238. This one was in a hidden place between many list appends for which no test existed. I have also added a new test for this part of the code.
